### ISSUE TITLE
[development] add A* algorithm

### ISSUE THREAD

**Issue by Minki-Kim95** [18-2-SKKU-OSS/2018-2-OSS-L1#1]
[A* 알고리즘]
주어진 출발 꼭짓점에서부터 목표 꼭짓점까지 가는 최단 경로를 찾아내는 그래프/트리 탐색 알고리즘

[제안이유]
기본적인 알고리즘인데 누락되어 있다

[특이사항]
실제 프로젝트에서도 issue로 등록되어 있는 사항 pull-request 받을 가능성 높음

**Comment by orist22** [comment]
확인했습니다

**Comment by orist22** [comment]
구현 후 pull request 요청했지만 코드 규칙 문제로 conflict 발생했습니다.

수정 후 다시 요청 보내보겠습니다.

**Comment by orist22** [comment]
코드 규칙에 맞춰 수정한 뒤 다시 pull request 보냈습니다.
