### ISSUE TITLE
[to do] Tarjan Algorithm Exist

### ISSUE THREAD

**Issue by kjy276** [18-2-SKKU-OSS/2018-2-OSS-L1#12]
Tarjan Algorithm으로 SCC(Strong Connected Component) 찾는 부분이 없다고 생각했는데
graph/bridges 
graph/articulation-points
에서 Tarjan Algorithm 내용을 서술해놨었네요

여기 없는 다른 알고리즘을 찾아보겠습니다

**Comment by orist22** [comment]
확인했습니다. 기여하실 수 있는 다른 알고리즘을 한번 찾아봐주세요.
