### ISSUE TITLE
[BUG] astar 삭제되었었음

### ISSUE THREAD

**Issue by kjy276** [18-2-SKKU-OSS/2018-2-OSS-L1#14]
git pull 로 최신 상태로 만든 후
git add ccw 명령어로 ccw 파일을 추가한 후 commit 하고
git push 했더니 master branch에서 astar.js 파일이 삭제되었습니다
대신 그 자리에 .DS_Store 라는 이상한 파일이 생겼었습니다

로컬 저장소에는 astar.js 파일이 멀쩡히 있고 웹에도 기록이 남아 있어서 백업해둔 후 로컬에서 astar.js를 rm -f 한 후 원본을 다시 add 하고 commit하니 해결되었습니다

**Comment by orist22** [comment]
확인했습니다
