### ISSUE TITLE
[수정제안] 한글 번역

### ISSUE THREAD

**Issue by Minki-Kim95** [18-2-SKKU-OSS/2018-2-OSS-L1#2]
한글 번역된 readMe를 보면 버블소트를 거품 정렬이라고 되있는 부분이 있는데 이 부분 혹시 버블 정렬로 바꾸는거 어떻게 생각하나요? 아니면 버블 정렬 뒤에 괄호치고 bubble sort라고 쓰는 것도 생각중입니다

**Comment by orist22** [comment]
많은 문서에서 bubble sort의 한국어 번역을 거품 정렬이라고 표기하고 있어 그대로 사용해도 괜찮을 것 같습니다.

**Comment by Minki-Kim95** [comment]
그러면 일단 영어로 부연설명만 다는걸로 한번 제가 수정해보겠습니다
