### ISSUE TITLE
[Page] Team Page link

### ISSUE THREAD

**Issue by yunji-yunji** [18-2-SKKU-OSS/2018-2-OSS-L1#21]
팀 페이지와 깃 허브 메뉴를 연동하는 부분을 페이지의 어느 부분에 추가하는 것이 좋을까요?

**Comment by orist22** [comment]
페이지 상단 제목 하단에 추가하면 좋을 것 같습니다

**Comment by yunji-yunji** [comment]
저 제목이 config file에 description 형태로 되어있어서
그 위치에 거는 것은 조금 힘들 것 같습니다.
대신 메뉴 별로 포스트를 작성해서 하단에 링크를 달아 놓았습니다.
좋은 의견 감사합니다.😊
