### ISSUE TITLE
[질문] Sleepsort pullrequest에 관하여

### ISSUE THREAD

**Issue by Minki-Kim95** [18-2-SKKU-OSS/2018-2-OSS-L1#26]
풀리퀘스트를 날려보려 하니 큰 문제가 있습니다
우선 이 알고리즘 자체가 원소에 지정되있는 시간 만큼 기다렸다 새로운 array에 집어넣는 식으로 작동하는 거라서 time complexity를  예측 할 수 없는 알고리즘 이기도 하고 위키에도 등록안되있을 정도로 몇몇 사이트에서만 농담식으로 떠돌아 다니는 sorting방식이였습니다.
마음같아선 풀리퀘를 날리고 싶지만 이러한 부분들 때문에 절대 test도 통과 못하고 받아줄 가능성도 적어서 풀리퀘스트 날리는건 포기해야 할것 같아요

**Comment by Minki-Kim95** [comment]
아니면 저거를 원래 프로젝트에 반영할 수 있는 다른 방법없을까요?

**Comment by orist22** [comment]
일단 구현에 의미를 두고 Pull Request는 보류하는 걸로 하죠
