### ISSUE TITLE
[development]Javascript 실행환경

### ISSUE THREAD

**Issue by orist22** [18-2-SKKU-OSS/2018-2-OSS-L1#3]
Javascript 개발 시 아래 사이트에서 html 파일없이 바로 Javascript code를 실행해 볼 수 있어 유용할 것 같습니다.
아래 링크로 접속하시면 됩니다.

http://jsfiddle.net/

**Comment by Minki-Kim95** [comment]
좋은 정보 감사합니다!

**Comment by yunji-yunji** [comment]
저는 npm으로 실행해보고 있었는데 좋은 정보 감사합니다!
