### ISSUE TITLE
[Notice]node_modules add 관련 issue

### ISSUE THREAD

**Issue by Minki-Kim95** [18-2-SKKU-OSS/2018-2-OSS-L1#31]
제가 git add를 하다가 실수로 전체 추가를 해서 node_modules가 프로젝트에 추가된적이 있었습니다.
저게 추가되면 프로젝트의 pull받는 시간이 길어지니 add할 때 주의해 주시기 바랍니다.
만약 실수로 추가 하시게 된다면 파일을 로컬 레퍼지토리에서 삭제하고 git add한 다음에 원격 레퍼지토리에 반영해주고 다시 npm install을 하면됩니다.

**Comment by kjy276** [comment]
확인했습니다
