### ISSUE TITLE
[to do] GitHub page

### ISSUE THREAD

**Issue by yunji-yunji** [18-2-SKKU-OSS/2018-2-OSS-L1#4]
저희 깃허브 페이지 만들어야 합니다!
언제 만들지 일정 정합시다!!

**Comment by Minki-Kim95** [comment]
내일 수업시간 직전에 모여서 한번 해보는 것도 좋을것 같아요

**Comment by orist22** [comment]
지금 github page가 John Smith로 되어있는데 이 부분 확인 부탁드립니다.

**Comment by yunji-yunji** [comment]
확인했습니다. 새로운 테마로 변경하였습니다.
