### ISSUE TITLE
[development]Sleep sort 추가

### ISSUE THREAD

**Issue by Minki-Kim95** [18-2-SKKU-OSS/2018-2-OSS-L1#5]
정렬 파트에서 sleep sort 한번 구현해보겠습니다

**Comment by orist22** [comment]
확인했습니다

**Comment by orist22** [comment]
sleep sort 아직 구현 안하셨으면 제가 해봐도 될까요?

구현하고 있던 알고리즘이 끝나서 새로 만들 알고리즘을 찾는 중입니다.

**Comment by orist22** [comment]
이미 구현 하셨네요

issue close하겠습니다

**Comment by Minki-Kim95** [comment]
진행중이라 완료되면 제가 close하겠습니다
