### ISSUE TITLE
[Error] commit error

### ISSUE THREAD

**Issue by yunji-yunji** [18-2-SKKU-OSS/2018-2-OSS-L1#7]
커밋하려고 하는데 자꾸 에러가 뜹니다....

![image](https://user-images.githubusercontent.com/39113997/49421499-8ff29500-f7d3-11e8-8b32-170949f48468.png)

**Comment by yunji-yunji** [comment]
git commit -n 으로 하면 커밋은 되는데 push가 안되요..

**Comment by orist22** [comment]
다른 디렉토리에서 git init 다시 해보실래요?

**Comment by yunji-yunji** [comment]
해결했습니다! 감사합니다ㅎㅎ
